Update ESP32_IO_Expander to latest master
ESP32_IO_Expander v0.0.3 doesn't have the C++ wrapper headers that
the latest ESP32_Display_Panel master requires.

Error:
  fatal error: esp_io_expander.hpp: No such file or directory

Solution:
  Use latest master of ESP32_IO_Expander (remove #v0.0.3 tag)

The newer version has the C++ wrapper headers alongside the C API.