Add ESP32_ArduinoLibUtils library dependency
The latest ESP32_Display_Panel master requires esp_lib_utils.h which
is provided by the ESP32_ArduinoLibUtils library.

Error:
  esp_panel_utils_map.hpp:9:10: fatal error: esp_lib_utils.h: No such file or directory

Solution:
  Add https://github.com/esp-arduino-libs/ESP32_ArduinoLibUtils.git

This is a new dependency added in newer versions of ESP32_Display_Panel.